### ISSUE TITLE
Server Tomcat v8.0 Server at localhost failed to start.

### ISSUE THREAD

**Issue by AnkitaSankhe** [DKrunal/CakeShop#1]
Below is the StackTrace-
[error.txt](https://github.com/DKrunal/CakeShop/files/726134/error.txt)
ScreenShot
![error](https://cloud.githubusercontent.com/assets/20534512/22241104/fb54bf14-e243-11e6-97e6-8473e904e50e.png)

**Comment by AnkitaSankhe** [comment]
This error is mainly related to tomcat
1)If you added any jar in lib folder of tomcat server - remove it
2)Clean the tomcat server(right click on server and clean)
3)Are you using older version of tomcat?
Eclipse neon -> Tomcat 9
4)Try to add servlet-api dependency in pom.xmo with 'provided' scope
If all these does not work.
try deleting .m2 folder and start eclipse again.

**Comment by abhinavsingh56** [comment]
deleting and readding tomcat server may help or if  it is a maven project look for some dependencies need by tomcat
